In [1]:
import os
import pandas as pd
import pyodbc
import mysql.connector

# Excel file path
excel_file_path = r'C:\Users\Awan\Downloads\DCS126_RGHAURI.xlsx'

# SQL Server connection details with Windows authentication
server_name = 'IMRANKHAN\\SQLEXPRESS'  # Note the double backslash
database_name = 'postgres'

# Establish a connection to the SQL Server database with integrated security
conn_str = f'DRIVER={{SQL Server}};SERVER={server_name};DATABASE={database_name};Trusted_Connection=yes;'
conn = pyodbc.connect(conn_str)
cursor = conn.cursor()

try:
    # Read Excel file into a pandas DataFrame starting from row 9
    df = pd.read_excel(excel_file_path, skiprows=7)
    # Convert all columns to strings (varchar(50))
    df = df.applymap(str)
    
    for index, row in df.iterrows():
        # Check if a row with the same key already exists
        cursor.execute('''
            SELECT 1 
            FROM data_report 
            WHERE 
                CRN_IN = ? AND ContractID = ? AND PerformerID = ? AND 
                PatientSurname = ? AND PatientForename = ? AND DateOfBirth = ?
        ''',
        (row['CRN/IN'], row['Contract ID'], row['Performer ID'], row['Patient Surname'],
         row['Patient Forename'], row['Date of Birth']))
        
        existing_row = cursor.fetchone()

        if existing_row:
            # Update the existing row
            cursor.execute('''
                UPDATE data_report 
                SET 
                    Errors = ?, PatientCharge = ?, Period = ?, Units = ?, 
                    ContraPeriod_Units_PCharge = ?, [NHS Number] = ?, 
                    ProcessingDate = ?, Status = ?, FormType = ?, 
                    Created_Amended_Deletedby = ?, Creation_Amend_DeletioDate = ?
                WHERE 
                    CRN_IN = ? AND ContractID = ? AND PerformerID = ? AND 
                    PatientSurname = ? AND PatientForename = ? AND DateOfBirth = ?
            ''',
            (row['Errors'], row['Patient Charge'], row['Period'], row['Units'],
             row['Contra Period, Units, P. Charge'], row['NHS Number'],
             row['Processing Date'], row['Status'], row['Form Type'],
             row['Created/Amended/Deleted by'], row['Creation/Amend/Deletion Date'],
             row['CRN/IN'], row['Contract ID'], row['Performer ID'],
             row['Patient Surname'], row['Patient Forename'], row['Date of Birth']))
        else:
            # Insert a new row if no matching row is found
            cursor.execute('''
                INSERT INTO data_report 
                (CRN_IN, ContractID, PerformerID, Errors, PatientSurname, PatientForename, DateOfBirth, 
                TreatmentStartDate, TreatmentEndDate, PatientCharge, Period, Units, ContraPeriod_Units_PCharge, 
                [NHS Number], ProcessingDate, Status, FormType, Created_Amended_Deletedby, Creation_Amend_DeletioDate)
                VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            ''', 
            (row['CRN/IN'], row['Contract ID'], row['Performer ID'], row['Errors'], row['Patient Surname'],
             row['Patient Forename'], row['Date of Birth'], row['Treatment Start Date'], row['Treatment End Date'],
             row['Patient Charge'], row['Period'], row['Units'], row['Contra Period, Units, P. Charge'],
             row['NHS Number'], row['Processing Date'], row['Status'], row['Form Type'],
             row['Created/Amended/Deleted by'], row['Creation/Amend/Deletion Date']))

    # Commit the changes
    conn.commit()
  

    # Delete the Excel file after successful data insertion or update
    os.remove(excel_file_path)
   

except Exception as e:
    print(f"Error: {e}")

finally:
    # Close the cursor and connection
    cursor.close()
    conn.close()

OperationalError: ('08001', '[08001] [Microsoft][ODBC SQL Server Driver][DBNETLIB]SQL Server does not exist or access denied. (17) (SQLDriverConnect); [08001] [Microsoft][ODBC SQL Server Driver][DBNETLIB]ConnectionOpen (Connect()). (53)')

In [9]:
import os
import pandas as pd
import pyodbc
import mysql.connector

# Excel file path
excel_file_path = r'C:\Users\Awan\Downloads\DCS126_RGHAURI (5).xlsx'
username = 'root'
password = ''
database_name = 'new'
host = 'localhost'  # e.g., 'localhost'

# Establish connection to MySQL
try:
    conn = mysql.connector.connect(
        user=username,
        password=password,
        host=host,
        database=database_name
    )
    print("Connected to MySQL database:", conn.database)
    cursor = conn.cursor()
    # Read Excel file into a pandas DataFrame starting from row 9
    df = pd.read_excel(excel_file_path, skiprows=7)
    # Convert all columns to strings (varchar(50))
    df = df.applymap(str)
    
    for index, row in df.iterrows():
        # Check if a row with the same key already exists
        cursor.execute('''
            SELECT 1 
            FROM data_report 
            WHERE 
                CRN_IN = %s AND ContractID = %s AND PerformerID = %s AND 
                PatientSurname = %s AND PatientForename = %s AND DateOfBirth = %s
        ''',
        (row['CRN/IN'], row['Contract ID'], row['Personal ID'], row['Patient Surname'],
         row['Patient Forename'], row['Date of Birth']))
        
        existing_row = cursor.fetchone()

        if existing_row:
            # Update the existing row
            cursor.execute('''
                UPDATE data_report 
                SET 
                    Errors = %s, PatientCharge = %s, Period = %s, Units = %s, 
                    ContraPeriod_Units_PCharge = %s, NHSNumber = %s, 
                    ProcessingDate = %s, Status = %s, FormType = %s, 
                    CreatedAmendedDeletedby = %s, CreationAmendDeletionDate = %s
                WHERE 
                    CRN_IN = %s AND ContractID = %s AND PerformerID = %s AND 
                    PatientSurname = %s AND PatientForename = %s AND DateOfBirth = %s
            ''',
            (row['Errors'], row['Patient Charge'], row['Period'], row['Units'],
             row['Contra Period, Units, P. Charge'], row['NHS Number'],
             row['Processing Date'], row['Status'], row['Form Type'],
             row['Created/Amended/Deleted by'], row['Creation/Amend/Deletion Date'],
             row['CRN/IN'], row['Contract ID'], row['Personal ID'],
             row['Patient Surname'], row['Patient Forename'], row['Date of Birth']))
            print(f"Row {index} updated successfully.")
        else:
            # Insert a new row if no matching row is found
            cursor.execute('''
                INSERT INTO data_report 
                (CRN_IN, ContractID, PerformerID, Errors, PatientSurname, PatientForename, DateOfBirth, 
                TreatmentStartDate, TreatmentEndDate, PatientCharge, Period, Units, ContraPeriod_Units_PCharge, 
                NHSNumber, ProcessingDate, Status, FormType, CreatedAmendedDeletedby, CreationAmendDeletionDate)
                VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
            ''', 
                           
            (row['CRN/IN'], row['Contract ID'], row['Personal ID'], row['Errors'], row['Patient Surname'],
             row['Patient Forename'], row['Date of Birth'], row['Treatment Start Date'], row['Treatment End Date'],
             row['Patient Charge'], row['Period'], row['Units'], row['Contra Period, Units, P. Charge'],
             row['NHS Number'], row['Processing Date'], row['Status'], row['Form Type'],
             row['Created/Amended/Deleted by'], row['Creation/Amend/Deletion Date']))
            print(f"Row {index} inserted successfully.")
    # Commit the changes
    conn.commit()
  

    # Delete the Excel file after successful data insertion or update
    os.remove(excel_file_path)
   

except Exception as e:
    print(f"Error: {e}")

finally:
    # Close the cursor and connection
    cursor.close()
    conn.close()

Connected to MySQL database: new
Row 0 inserted successfully.
Row 1 inserted successfully.
Row 2 inserted successfully.
Row 3 inserted successfully.
Row 4 inserted successfully.
Row 5 inserted successfully.
Row 6 inserted successfully.
Row 7 inserted successfully.
Row 8 inserted successfully.
Row 9 inserted successfully.
Row 10 inserted successfully.
Row 11 inserted successfully.
Row 12 inserted successfully.
Row 13 inserted successfully.
Row 14 inserted successfully.
Row 15 inserted successfully.
Row 16 inserted successfully.
Row 17 inserted successfully.
Row 18 inserted successfully.
Row 19 inserted successfully.
Row 20 inserted successfully.
Row 21 inserted successfully.