In [2]:
#pdf_path = r'C:\Users\Awan\Downloads\_Att9287647.pdf'
pdf_path = r'D:\Interrnship\Statement 23-24\Statement 23-24\Sch Issued 1st Aug 23 will be paid 1st Sept 23\3954630007.pdf'

In [3]:
import PyPDF2

def extract_text_from_pdf(pdf_path):
    text_per_page = []
    with open(pdf_path, 'rb') as file:
        pdf_reader = PyPDF2.PdfReader(file)
        num_pages = len(pdf_reader.pages)
        for page_num in range(num_pages):
            page = pdf_reader.pages[page_num]
            text = page.extract_text()
            text_per_page.append(text)
    return text_per_page

if __name__ == "__main__":
    pdf_text = extract_text_from_pdf(pdf_path)
    '''for page_num, text in enumerate(extracted_text, start=1):
        print(f"Page {page_num}:")
        print(text.strip())
        print("\n---\n")'''

In [4]:
import PyPDF2
#pdf_path = r'C:\Users\Awan\Downloads\_Att9287647.pdf'
def pdf_text_from_pdf(pdf_path):
    text_per_page = []
    with open(pdf_path, 'rb') as file:
        pdf_reader = PyPDF2.PdfReader(file)
        num_pages = len(pdf_reader.pages)
        for page_num in range(num_pages):
            page = pdf_reader.pages[page_num]
            text = page.extract_text()
            text_per_page.append(text)
    return text_per_page
def extract_statement_references_from_text(pdf_text):
    statement_reference = None  # Initialize statement reference variable
    for text in pdf_text:
        if statement_reference is None:  # Check if statement reference is not assigned yet
            statement_reference_match = re.search(r'Statement\s*Reference\s*([\d/]+)', text)
            if statement_reference_match:
                statement_reference = statement_reference_match.group(1)
                break  # Break loop after finding the first statement reference
    return statement_reference
def extract_text_from_pdf(pdf_path):
    text_per_page = []
    with open(pdf_path, 'rb') as file:
        pdf_reader = PyPDF2.PdfReader(file)
        num_pages = len(pdf_reader.pages)
        for page_num in range(num_pages):
            page = pdf_reader.pages[page_num]
            text = page.extract_text()
            text_per_page.append(text)
            # Check if the text "Contract Monthly Pay Statement" is in the extracted text
            if "Contract Monthly Pay Statement" in text:
                break  # Stop extracting text from further pages
    return text_per_page
import PyPDF2


if __name__ == "__main__":
    pdf_text = pdf_text_from_pdf(pdf_path)
    statement_reference = extract_statement_references_from_text(pdf_text)
    
    if statement_reference:
        print("Extracted Statement Reference:", statement_reference)
    else:
        print("No Statement Reference found in the PDF.")
    
    extracted_text = extract_text_from_pdf(pdf_path)
    found_text = False  # Flag to check if the desired text is found
    contract_monthly_pay_statement_text = ""  # Initialize empty string to store the desired text
    for page_num, text in enumerate(extracted_text, start=1):
        if found_text:
            contract_monthly_pay_statement_text += text.strip() + "\n---\n"  # Append the text to the output
        elif "Contract Monthly Pay Statement" in text:
            found_text = True  # Set the flag to True when the desired text is found
            contract_monthly_pay_statement_text += text.strip() + "\n---\n"  # Append the text to the output

    extracted_text = extract_text_from_pdf(pdf_path)
    found_start = False
    contract = ""  # Initialize empty string to store the desired text
    for page_num, text in enumerate(extracted_text, start=1):
        if found_start:
            if "CONTRACT" in text:
                break
            contract += text.strip() + "\n"
        elif "CONTRACT" in text:
            found_start = True
            # Find the index of the start of "Contract Monthly Pay Statement" and "CONTRACT"
            start_index = text.find("CONTRACT") + len("CONTRACT")
            end_index = text.find("If ")
            # Append the text between these indices
            contract += text[start_index:end_index].strip() + "\n"

    # Splitting the contract string into Contract_ID and Contract_Name
    contract_lines = contract.split("\n", 1)  # Splitting into two parts at the first newline

    # Assuming the first part is Contract_ID and the second part is Contract_Name
    contract_id = contract_lines[0].strip()
    Contract_Name = contract_lines[1].strip()
    Contract_ID = ''.join(filter(str.isdigit, contract_id))
    print("Contract_ID:", Contract_ID)

Extracted Statement Reference: 2324/04
Contract_ID: 3954630007

In [24]:
import re
import pandas as pd
def pdf_text_from_pdf(pdf_path):
    text_per_page = []
    with open(pdf_path, 'rb') as file:
        pdf_reader = PyPDF2.PdfReader(file)
        num_pages = len(pdf_reader.pages)
        for page_num in range(num_pages):
            page = pdf_reader.pages[page_num]
            text = page.extract_text()
            text_per_page.append(text)
    return text_per_page
def extract_statement_references_from_text(pdf_text):
    statement_reference = None  # Initialize statement reference variable
    for text in pdf_text:
        if statement_reference is None:  # Check if statement reference is not assigned yet
            statement_reference_match = re.search(r'Statement\s*Reference\s*([\d/]+)', text)
            if statement_reference_match:
                statement_reference = statement_reference_match.group(1)
                break  # Break loop after finding the first statement reference
    return statement_reference
def extract_text_from_pdf(pdf_path):
    text_per_page = []
    with open(pdf_path, 'rb') as file:
        pdf_reader = PyPDF2.PdfReader(file)
        num_pages = len(pdf_reader.pages)
        for page_num in range(num_pages):
            page = pdf_reader.pages[page_num]
            text = page.extract_text()
            text_per_page.append(text)
            # Check if the text "Contract Monthly Pay Statement" is in the extracted text
            if "Contract Monthly Pay Statement" in text:
                break  # Stop extracting text from further pages
    return text_per_page


def extract_performers_superannuation_table(pdf_text):
    # Define the start and end patterns for the table
    start_pattern = r'Performers\' Superannuation Contribution'
    end_pattern = r'Patients\' Charges'

    # Find the start and end positions of the table
    start_match = re.search(start_pattern, pdf_text)
    end_match = re.search(end_pattern, pdf_text)

    # If both start and end patterns are found, extract the table text
    if start_match and end_match:
        table_text = pdf_text[start_match.end():end_match.start()].strip()
        return table_text
    else:
        return None
def extract_rows_from_text(text):
    # Define a more flexible pattern to capture rows
    pattern = r'(\d+)\s+([A-Za-z\s]+)@?\s+([\d.]+)%\s*(-?£[\d.,]+)'
    #rows = re.findall(r'(\d+)\s+([A-Za-z\s]+)@?\s+([\d.]+)%\s+£([\d.]+)', cleaned_table_text)
    
    # Find all matches in the text
    matches = re.findall(pattern, cleaned_text)
    
    # Return a list of matched rows
    return matches

def format_table(rows, Contract_ID, statement_reference):
    formatted_rows = []
    for row in rows:
               # Extract the numeric part of the amount string and convert to float
        amount_str = re.sub(r'[^.\d]', '', row[3])  # Remove all non-numeric characters except '.'
        amount = float(amount_str)  # Convert to float
        
        formatted_row = {
            "Contract_ID": Contract_ID,
            "Statement_Reference": statement_reference,
            "Performer_ID": row[0],
            "Name": row[1].strip(),
            "Percentage": row[2],
            "Amount": amount
        }
        formatted_rows.append(formatted_row)
    return formatted_rows
def extract_performers_non_superannuable_deductions(pdf_text):
    # Define the start and end patterns for the table
    start_pattern = r'Non-Superannuable Deductions\s*Statutory Levy'
    end_pattern = r'(?:Performers\' Net Pensionable Earnings|$)'  # End pattern is either end of table or next section

    # Find the start and end positions of the table
    start_match = re.search(start_pattern, pdf_text)
    end_match = re.search(end_pattern, pdf_text)

    # If both start and end patterns are found, extract the table text
    if start_match and end_match:
        table_text = pdf_text[start_match.end():end_match.start()]
        return table_text.strip()
    else:
        return None

def format_tablenon_superannuable_deductions(table_text, Contract_ID, statement_reference):
    # Extracting rows using regular expression
    rows = re.findall(r'(\d+)\s+([A-Za-z\s]+)\s+£([\d.]+)', table_text)
    

    # Formatting the rows into desired format
    formatted_rows = []
    for row in rows:
        formatted_row = {
            "Contract_ID": Contract_ID,
            "Statement_Reference": statement_reference,
            "Performer_ID": row[0],
            "Performer_Name": row[1],
            "Amount": row[2]
            
            
        }
        formatted_rows.append(formatted_row)

    return formatted_rows

def extract_units_of_dental_activity(text_per_page):
    start_pattern = "Units of Dental Activity per Performer"
    #start_pattern = "Units of Dental Activity per Clinician"
    end_pattern = "THIS STATEMENT SHOULD BE RETAINED FOR TAX PURPOSES"

    relevant_text = ""
    for page_text in text_per_page:
        start_index = page_text.find(start_pattern)
        if start_index != -1:
            end_index = page_text.find(end_pattern, start_index)
            if end_index != -1:
                relevant_text += page_text[start_index:end_index]
            else:
                relevant_text += page_text[start_index:]
    return relevant_text

def parse_performers(text):
    performer_data = re.findall(r'\b(\d+)\s+([A-Za-z\s]+)\s+Current', text)
    performer_ids, performer_names = zip(*performer_data)
    return performer_ids, performer_names

def extract_current_financial_year_rows(text, pattern, year_col_name, amount_col_name):
    current_year_rows = []
    lines = text.strip().split('\n')
    for line in lines:
        match = re.search(pattern, line)
        if match:
            year = match.group(1) if match.group(1) else '0'  # If year is missing, consider it as '0'
            current_year_rows.append({year_col_name: year, amount_col_name: match.group(2)})
    return current_year_rows


if __name__ == "__main__":
    # Extract the table text
    pdf_text = pdf_text_from_pdf(pdf_path)
    complete_pdf_text = "\n".join(pdf_text)
    performers_superannuation_table_text = extract_performers_superannuation_table(complete_pdf_text)
    cleaned_table_text = re.sub(r'\(\d+\)', '', performers_superannuation_table_text)
    pattern = r"Performers' Added Benefit.*$"

    # Use regex to substitute the matched pattern with an empty string
    cleaned_text = re.sub(pattern, '', cleaned_table_text, flags=re.DOTALL)

    # Trim any leading or trailing whitespace
    cleaned_text = cleaned_text.strip()
    



    
    pdf_text = pdf_text_from_pdf(pdf_path)
    statement_reference = extract_statement_references_from_text(pdf_text)
    
    if statement_reference:
        print("Extracted Statement Reference:", statement_reference)
    else:
        print("No Statement Reference found in the PDF.")
    
    extracted_text = extract_text_from_pdf(pdf_path)
    found_text = False  # Flag to check if the desired text is found
    contract_monthly_pay_statement_text = ""  # Initialize empty string to store the desired text
    for page_num, text in enumerate(extracted_text, start=1):
        if found_text:
            contract_monthly_pay_statement_text += text.strip() + "\n---\n"  # Append the text to the output
        elif "Contract Monthly Pay Statement" in text:
            found_text = True  # Set the flag to True when the desired text is found
            contract_monthly_pay_statement_text += text.strip() + "\n---\n"  # Append the text to the output

    extracted_text = extract_text_from_pdf(pdf_path)
    found_start = False
    contract = ""  # Initialize empty string to store the desired text
    for page_num, text in enumerate(extracted_text, start=1):
        if found_start:
            if "CONTRACT" in text:
                break
            contract += text.strip() + "\n"
        elif "CONTRACT" in text:
            found_start = True
            # Find the index of the start of "Contract Monthly Pay Statement" and "CONTRACT"
            start_index = text.find("CONTRACT") + len("CONTRACT")
            end_index = text.find("If ")
            # Append the text between these indices
            contract += text[start_index:end_index].strip() + "\n"

    # Splitting the contract string into Contract_ID and Contract_Name
    contract_lines = contract.split("\n", 1)  # Splitting into two parts at the first newline

    # Assuming the first part is Contract_ID and the second part is Contract_Name
    contract_id = contract_lines[0].strip()
    Contract_Name = contract_lines[1].strip()
    Contract_ID = ''.join(filter(str.isdigit, contract_id))
    print("Contract_ID:", Contract_ID)
    # Extract rows using the updated pattern
    rows = extract_rows_from_text(cleaned_text)

    
    # Format the extracted rows into DataFrame
    formatted_table = format_table(rows, Contract_ID, statement_reference)
    df2 = pd.DataFrame(formatted_table)
    
    # Display the DataFrame
    
    print("Performers' Superannution Deductions Statutory Levy Table:")
    print(df2)
    
    performers_non_superannuation_table_text = extract_performers_non_superannuable_deductions(complete_pdf_text)

    # Print the extracted table text
    if performers_non_superannuation_table_text:
        print("Performers' Non-Superannuable Deductions Statutory Levy Table:")
        #print(performers_non_superannuation_table_text)

        # Format the table text
        formatted_table = format_table_non_superannuable_deductions(performers_non_superannuation_table_text, Contract_ID, statement_reference)

        # Convert the formatted table to DataFrame
        df = pd.DataFrame(formatted_table)

        # Print DataFrame
        #print(df)
        
        
# Create a boolean mask to identify rows where 'Performer_Name' is either 'Contract' or 'Superannuable'
        mask = ~df['Performer_Name'].isin(['Contract', 'Superannuable'])

# Apply the mask to filter out rows that do not match the conditions
        df3 = df[mask]

# df_filtered now contains only the rows where 'Performer_Name' is neither 'Contract' nor 'Superannuable'
        
        print(df3)
    else:
        print("Performers' Non-Superannuable Deductions Statutory Levy Table not found in the PDF text.")
    
    relevant_text = extract_units_of_dental_activity(pdf_text)
    
    # Parse performer data
    performer_ids, performer_names = parse_performers(relevant_text)
    
    # Create performer DataFrame
    df_performers = pd.DataFrame({'Contract_ID': Contract_ID,'Statement_Reference':statement_reference,'Performer_ID': performer_ids, 'Name': performer_names})
    
    # Extract financial year rows
    current_year_rows = extract_current_financial_year_rows(relevant_text, 
                                                            r'Current Financial Year (\d{4}/\d{2})\s+([\d.]+)',
                                                            'Current_Financial_Year', 
                                                            'Current_Financial_Year_Amount')
    
    last_year_rows = extract_current_financial_year_rows(relevant_text, 
                                                            r'Last Financial Year (\d{4}/\d{2})\s+([\d.]+)',
                                                            'Last_Financial_Year', 
                                                            'Last_Financial_Year_Amount')

    other_year_rows = extract_current_financial_year_rows(relevant_text, 
                                                            r'Other Financial Years(?: (\d{4}/\d{2}))?\s+([\d.]+)',
                                                            'Other_Financial_Years', 
                                                            'Other_Financial_Year_Amount')

    # Create financial year DataFrames
    df_current = pd.DataFrame(current_year_rows)
    df_last = pd.DataFrame(last_year_rows)
    df_other = pd.DataFrame(other_year_rows)
    
    # Concatenate financial year DataFrames
    df_financial_years = pd.concat([df_current, df_last, df_other], axis=1)
    
    # Print combined DataFrame
    combined_df = pd.concat([df_performers, df_financial_years], axis=1)
    df4 =combined_df 
    
    print("Performers' Units of Dental Activity Table:")
    print(df4)

Extracted Statement Reference: 2324/04
Contract_ID: 3954630007
Performers' Superannution Deductions Statutory Levy Table:
   Contract_ID Statement_Reference Performer_ID                 Name  \
0   3954630007             2324/04       364207           AJ ABULHAB
1   3954630007             2324/04       114847             Coughlan
2   3954630007             2324/04       651133             S GHAURI
3   3954630007             2324/04       887048  I HAMDY ABD ELRAZEK
4   3954630007             2324/04       887048  I HAMDY ABD ELRAZEK
5   3954630007             2324/04       887048  I HAMDY ABD ELRAZEK
6   3954630007             2324/04       786616       AK JAISINGHANI
7   3954630007             2324/04       453390             JS MALIK
8   3954630007             2324/04       107389             ZM MIRZA
9   3954630007             2324/04       107389             ZM MIRZA
10  3954630007             2324/04       476617            AD MISTRY
11  3954630007             2324/04       111766             Ja Malik
12  3954630007             2324/04       111766             Ja Malik
13  3954630007             2324/04       111766             Ja Malik
14  3954630007             2324/04       623504              JS UBHI
15  3954630007             2324/04       115616               NZ ZIA
16  3954630007             2324/04       115616               NZ ZIA

   Percentage  Amount
0       11.60    4.75
1        7.70    3.80
2        5.10    0.23
3        5.00   11.80
4        5.10   12.90
5        5.10    4.12
6        9.80    0.82
7        5.10    4.30
8        5.10    0.18
9        5.10    0.16
10       6.80    2.84
11       9.30   79.10
12       9.80   45.50
13       9.80   18.54
14       6.10    4.21
15       9.80    1.00
16       9.80    1.85
Performers' Non-Superannuable Deductions Statutory Levy Table:
   Contract_ID Statement_Reference Performer_ID        Performer_Name Amount
1   3954630007             2324/04       364207            AJ ABULHAB   0.19
2   3954630007             2324/04       440914           S CHANDNANI   0.02
3   3954630007             2324/04       114847              Coughlan   0.28
4   3954630007             2324/04       651133              S GHAURI   0.02
5   3954630007             2324/04       887048   I HAMDY ABD ELRAZEK   0.21
6   3954630007             2324/04       786616        AK JAISINGHANI   0.04
7   3954630007             2324/04       105667  KRISHNA MURTHY GOWDA   2.99
8   3954630007             2324/04       453390              JS MALIK   0.38
9   3954630007             2324/04       107389              ZM MIRZA   0.02
10  3954630007             2324/04       476617             AD MISTRY   0.28
11  3954630007             2324/04       111766              Ja Malik   1.92
12  3954630007             2324/04       943436              L NAJJAR   2.35
13  3954630007             2324/04       604143             MT PAREKH   1.44
14  3954630007             2324/04       114436                  SAFI   0.74
15  3954630007             2324/04       106669              AS SINGH   0.02
16  3954630007             2324/04       623504               JS UBHI   0.28
17  3954630007             2324/04       115616                NZ ZIA   0.65
Performers' Units of Dental Activity Table:
  Contract_ID Statement_Reference Performer_ID         Name  \
0  3954630007             2324/04       440914  S CHANDNANI
1  3954630007             2324/04       651133     S GHAURI
2  3954630007             2324/04       476617    AD MISTRY
3  3954630007             2324/04       111766     Ja Malik
4  3954630007             2324/04       604143    MT PAREKH
5  3954630007             2324/04       114436         SAFI
6  3954630007             2324/04       695483     F SATTAR

  Current_Financial_Year Current_Financial_Year_Amount Last_Financial_Year  \
0                2023/24                         14.40             2022/23
1                2023/24                          6.00             2022/23
2                2023/24                          3.60             2022/23
3                2023/24                         12.80             2022/23
4                2023/24                         13.20             2022/23
5                2023/24                          7.20             2022/23
6                2023/24                          4.60             2022/23

  Last_Financial_Year_Amount Other_Financial_Years Other_Financial_Year_Amount
0                       0.00                     0                        0.00
1                       0.00                     0                        0.00
2                       0.00                     0                        0.00
3                       0.00                     0                        0.00
4                       0.00                     0                        0.00
5                       0.00                     0                        0.00
6                       0.00                     0                        0.00

# Performers' Superannuation Contribution

In [ ]:
import re
import pandas as pd
import PyPDF2

def pdf_text_from_pdf(pdf_path):
    text_per_page = []
    with open(pdf_path, 'rb') as file:
        pdf_reader = PyPDF2.PdfReader(file)
        num_pages = len(pdf_reader.pages)
        for page_num in range(num_pages):
            page = pdf_reader.pages[page_num]
            text = page.extract_text()
            text_per_page.append(text)
    return text_per_page



def extract_performers_superannuation_table(pdf_text):
    # Define the start and end patterns for the table
    start_pattern = r'Performers\' Superannuation Contribution'
    end_pattern = r'Patients\' Charges'

    # Find the start and end positions of the table
    start_match = re.search(start_pattern, pdf_text)
    end_match = re.search(end_pattern, pdf_text)

    # If both start and end patterns are found, extract the table text
    if start_match and end_match:
        table_text = pdf_text[start_match.end():end_match.start()].strip()
        return table_text
    else:
        return None

def format_table(table_text):
    # Extracting rows using regular expression
    #rows = re.findall(r'(\d+)\s+([A-Z\s]+)@?\s+([\d.]+)%\s+£([\d.]+)', table_text)
    
    rows = re.findall(r'(\d+)\s+([A-Za-z\s]+)@?\s+([\d.]+)%\s+£([\d.]+)', table_text)
    
    pattern = r'(\d+)\s+([A-Za-z\s]+)@?\s+([\d.]+)%\s*(-?£[\d.,]+)'
    

    # Formatting the rows into desired format
    formatted_rows = []
    for row in rows:
        formatted_row = {
            "Performer_ID": row[0],
            "Name": row[1],
            "Percentage": row[2],
            "Amount ": row[3]
        }
        formatted_rows.append(formatted_row)

    return formatted_rows

if __name__ == "__main__":
    # Extract the table text
    pdf_text = pdf_text_from_pdf(pdf_path)
    complete_pdf_text = "\n".join(pdf_text)
    performers_superannuation_table_text = extract_performers_superannuation_table(complete_pdf_text)
    cleaned_table_text = re.sub(r'\(\d+\)', '', performers_superannuation_table_text)
    pattern = r"Performers' Added Benefit.*$"

    # Use regex to substitute the matched pattern with an empty string
    cleaned_text = re.sub(pattern, '', cleaned_table_text, flags=re.DOTALL)

    # Trim any leading or trailing whitespace
    cleaned_text = cleaned_text.strip()

    #print(cleaned_text)

    # Print the extracted table text
    if performers_superannuation_table_text:
        print("Performers' Superannuation Contribution Table:")
        formatted_table = format_table(cleaned_text )
        # Convert the formatted table to DataFrame
        df2 = pd.DataFrame(formatted_table)
        print(df2)
    else:
        print("Performers' Superannuation Contribution Table not found in the PDF text.")

In [ ]:
performers_superannuation_table_text

In [6]:

cleaned_table_text = re.sub(r'\(\d+\)', '', performers_superannuation_table_text)

In [7]:
cleaned_table_text

"£116.80\n364207 AJ ABULHAB @ 11.60% £4.75\n114847 Coughlan @ 7.70% £3.80\n651133 S GHAURI @ 5.10% £0.23\n887048 I HAMDY ABD ELRAZEK @ 5.00%  -£11.80\n887048 I HAMDY ABD ELRAZEK @ 5.10%  -£12.90\n887048 I HAMDY ABD ELRAZEK @ 5.10% -£4.12\n786616 AK JAISINGHANI @ 9.80% £0.82\n453390 JS MALIK @ 5.10% £4.30\n107389 ZM MIRZA @ 5.10%  -£0.18\n107389 ZM MIRZA @ 5.10% £0.16\n476617 AD MISTRY @ 6.80% £2.84\n111766 Ja Malik @ 9.30%  -£79.10\n111766 Ja Malik @ 9.80%  -£45.50\n \nTHIS STATEMENT SHOULD BE RETAINED FOR TAX PURPOSES\n2\nNATIONAL HEALTH SERVICE   \n Contract QRV   3954630007\nStatement Reference  2324/04  ASHIQ GHAURI AND SARFRAZ\nGHAURI T/A GHAURI DENTAL\nCENTRE\n   \nDate  01/08/23 VAT No. 654434729\nPAY STATEMENT\nNon Contributory Items Payments Deductions\n111766 Ja Malik @ 9.80% £18.54\n623504 JS UBHI @ 6.10% £4.21\n115616 NZ ZIA @ 9.80%  -£1.00\n115616 NZ ZIA @ 9.80% -£1.85\nPerformers' Added Benefit £0.75\n786616 AK JAISINGHANI @ 9.00% £0.75"

In [8]:
def clean_text(cleaned_table_text):
    # Define the pattern to identify and remove the unwanted section
    pattern = r'Performers\' Added Benefit.*$'

    # Use regex to substitute the matched pattern with an empty string
    cleaned_text = re.sub(pattern, '', cleaned_table_text, flags=re.DOTALL)
    
    return cleaned_text.strip()  # Trim any leading or trailing whitespace

cleaned_text = clean_text(cleaned_table_text)
print(cleaned_text)

£116.80
364207 AJ ABULHAB @ 11.60% £4.75
114847 Coughlan @ 7.70% £3.80
651133 S GHAURI @ 5.10% £0.23
887048 I HAMDY ABD ELRAZEK @ 5.00%  -£11.80
887048 I HAMDY ABD ELRAZEK @ 5.10%  -£12.90
887048 I HAMDY ABD ELRAZEK @ 5.10% -£4.12
786616 AK JAISINGHANI @ 9.80% £0.82
453390 JS MALIK @ 5.10% £4.30
107389 ZM MIRZA @ 5.10%  -£0.18
107389 ZM MIRZA @ 5.10% £0.16
476617 AD MISTRY @ 6.80% £2.84
111766 Ja Malik @ 9.30%  -£79.10
111766 Ja Malik @ 9.80%  -£45.50

THIS STATEMENT SHOULD BE RETAINED FOR TAX PURPOSES
2
NATIONAL HEALTH SERVICE
 Contract QRV   3954630007
Statement Reference  2324/04  ASHIQ GHAURI AND SARFRAZ
GHAURI T/A GHAURI DENTAL
CENTRE

Date  01/08/23 VAT No. 654434729
PAY STATEMENT
Non Contributory Items Payments Deductions
111766 Ja Malik @ 9.80% £18.54
623504 JS UBHI @ 6.10% £4.21
115616 NZ ZIA @ 9.80%  -£1.00
115616 NZ ZIA @ 9.80% -£1.85

In [9]:
pattern = r"Performers' Added Benefit.*$"

# Use regex to substitute the matched pattern with an empty string
cleaned_text = re.sub(pattern, '', cleaned_table_text, flags=re.DOTALL)

# Trim any leading or trailing whitespace
cleaned_text = cleaned_text.strip()

print(cleaned_text)

£116.80
364207 AJ ABULHAB @ 11.60% £4.75
114847 Coughlan @ 7.70% £3.80
651133 S GHAURI @ 5.10% £0.23
887048 I HAMDY ABD ELRAZEK @ 5.00%  -£11.80
887048 I HAMDY ABD ELRAZEK @ 5.10%  -£12.90
887048 I HAMDY ABD ELRAZEK @ 5.10% -£4.12
786616 AK JAISINGHANI @ 9.80% £0.82
453390 JS MALIK @ 5.10% £4.30
107389 ZM MIRZA @ 5.10%  -£0.18
107389 ZM MIRZA @ 5.10% £0.16
476617 AD MISTRY @ 6.80% £2.84
111766 Ja Malik @ 9.30%  -£79.10
111766 Ja Malik @ 9.80%  -£45.50

THIS STATEMENT SHOULD BE RETAINED FOR TAX PURPOSES
2
NATIONAL HEALTH SERVICE
 Contract QRV   3954630007
Statement Reference  2324/04  ASHIQ GHAURI AND SARFRAZ
GHAURI T/A GHAURI DENTAL
CENTRE

Date  01/08/23 VAT No. 654434729
PAY STATEMENT
Non Contributory Items Payments Deductions
111766 Ja Malik @ 9.80% £18.54
623504 JS UBHI @ 6.10% £4.21
115616 NZ ZIA @ 9.80%  -£1.00
115616 NZ ZIA @ 9.80% -£1.85

In [10]:
import re
import pandas as pd


def extract_performers_superannuation_table(pdf_text):
    # Define the start and end patterns for the table
    start_pattern = r'Performers\' Superannuation Contribution'
    end_pattern = r'Patients\' Charges'

    # Find the start and end positions of the table
    start_match = re.search(start_pattern, pdf_text)
    end_match = re.search(end_pattern, pdf_text)

    # If both start and end patterns are found, extract the table text
    if start_match and end_match:
        table_text = pdf_text[start_match.end():end_match.start()].strip()
        return table_text
    else:
        return None
if __name__ == "__main__":
    # Extract the table text
    pdf_text = pdf_text_from_pdf(pdf_path)
    complete_pdf_text = "\n".join(pdf_text)
    performers_superannuation_table_text = extract_performers_superannuation_table(complete_pdf_text)
    cleaned_table_text = re.sub(r'\(\d+\)', '', performers_superannuation_table_text)
    pattern = r"Performers' Added Benefit.*$"

    # Use regex to substitute the matched pattern with an empty string
    cleaned_text = re.sub(pattern, '', cleaned_table_text, flags=re.DOTALL)

    # Trim any leading or trailing whitespace
    cleaned_text = cleaned_text.strip()
    
def extract_rows_from_text(text):
    # Define a more flexible pattern to capture rows
    pattern = r'(\d+)\s+([A-Za-z\s]+)@?\s+([\d.]+)%\s*(-?£[\d.,]+)'
    #rows = re.findall(r'(\d+)\s+([A-Za-z\s]+)@?\s+([\d.]+)%\s+£([\d.]+)', cleaned_table_text)
    
    # Find all matches in the text
    matches = re.findall(pattern, cleaned_text)
    
    # Return a list of matched rows
    return matches

def format_table(rows, numeric_part, statement_reference):
    formatted_rows = []
    for row in rows:
               # Extract the numeric part of the amount string and convert to float
        amount_str = re.sub(r'[^.\d]', '', row[3])  # Remove all non-numeric characters except '.'
        amount = float(amount_str)  # Convert to float
        
        formatted_row = {
            "Contract_ID": Contract_ID,
            "Statement_Reference": statement_reference,
            "Performer_Id": row[0],
            "name": row[1].strip(),
            "percentage": row[2],
            "amount": amount
        }
        formatted_rows.append(formatted_row)
    return formatted_rows

if __name__ == "__main__":
    
    # Extract rows using the updated pattern
    rows = extract_rows_from_text(cleaned_text)

    
    # Format the extracted rows into DataFrame
    formatted_table = format_table(rows, Contract_ID, statement_reference)
    df2 = pd.DataFrame(formatted_table)
    
    # Display the DataFrame
    print(df2)

   Contract_ID Statement_Reference Performer_Id                 name  \
0   3954630007             2324/04       364207           AJ ABULHAB
1   3954630007             2324/04       114847             Coughlan
2   3954630007             2324/04       651133             S GHAURI
3   3954630007             2324/04       887048  I HAMDY ABD ELRAZEK
4   3954630007             2324/04       887048  I HAMDY ABD ELRAZEK
5   3954630007             2324/04       887048  I HAMDY ABD ELRAZEK
6   3954630007             2324/04       786616       AK JAISINGHANI
7   3954630007             2324/04       453390             JS MALIK
8   3954630007             2324/04       107389             ZM MIRZA
9   3954630007             2324/04       107389             ZM MIRZA
10  3954630007             2324/04       476617            AD MISTRY
11  3954630007             2324/04       111766             Ja Malik
12  3954630007             2324/04       111766             Ja Malik
13  3954630007             2324/04       111766             Ja Malik
14  3954630007             2324/04       623504              JS UBHI
15  3954630007             2324/04       115616               NZ ZIA
16  3954630007             2324/04       115616               NZ ZIA

   percentage  amount
0       11.60    4.75
1        7.70    3.80
2        5.10    0.23
3        5.00   11.80
4        5.10   12.90
5        5.10    4.12
6        9.80    0.82
7        5.10    4.30
8        5.10    0.18
9        5.10    0.16
10       6.80    2.84
11       9.30   79.10
12       9.80   45.50
13       9.80   18.54
14       6.10    4.21
15       9.80    1.00
16       9.80    1.85

# Non-Superannuable Deductions Statutory Levy

In [11]:
import re
import PyPDF2
import pandas as pd
'''
def extract_text_from_pdf(pdf_path):
    text_per_page = []
    with open(pdf_path, 'rb') as file:
        pdf_reader = PyPDF2.PdfReader(file)
        num_pages = len(pdf_reader.pages)
        for page_num in range(num_pages):
            page = pdf_reader.pages[page_num]
            text = page.extract_text()
            text_per_page.append(text)
    return text_per_page

def extract_statement_references_from_text(extracted_text):
    statement_references = []
    for text in extracted_text:
        statement_reference_match = re.search(r'Statement\s*Reference\s*([\d/]+)', text)
        if statement_reference_match:
            statement_reference = statement_reference_match.group(1)
            statement_references.append(statement_reference)
    return statement_references

'''

def extract_performers_non_superannuable_deductions(pdf_text):
    # Define the start and end patterns for the table
    start_pattern = r'Non-Superannuable Deductions\s*Statutory Levy'
    end_pattern = r'(?:Performers\' Net Pensionable Earnings|$)'  # End pattern is either end of table or next section

    # Find the start and end positions of the table
    start_match = re.search(start_pattern, pdf_text)
    end_match = re.search(end_pattern, pdf_text)

    # If both start and end patterns are found, extract the table text
    if start_match and end_match:
        table_text = pdf_text[start_match.end():end_match.start()]
        return table_text.strip()
    else:
        return None

def format_table_non_superannuable_deductions(table_text, numeric_part, statement_reference):
    # Extracting rows using regular expression
    rows = re.findall(r'(\d+)\s+([A-Za-z\s]+)\s+£([\d.]+)', table_text)
    

    # Formatting the rows into desired format
    formatted_rows = []
    for row in rows:
        formatted_row = {
            "Contract_ID": numeric_part,
            "Statement_Reference": statement_reference,
            "Performer_ID": row[0],
            "Performer_Name": row[1],
            "Amount": row[2]
            
            
        }
        formatted_rows.append(formatted_row)

    return formatted_rows

if __name__ == "__main__":
    # Extract statement references from PDF
    extracted_text = extract_text_from_pdf(pdf_path)
    statement_references = extract_statement_references_from_text(extracted_text)

    # Choose one statement reference for the sake of example (you might need to adjust this based on your actual data)
    statement_reference = statement_references[0] if statement_references else None

    # Extract contract ID from the PDF
    #contract_id = extract_contract_id("\n".join(extracted_text))

    # Extract the table text
    #pdf_path = 'BSA Statement 01 Highlighted.pdf'  # Change this to the path of your PDF file
    #extracted_text = extract_text_from_pdf(pdf_path)
    complete_pdf_text = "\n".join(extracted_text)
    performers_non_superannuation_table_text = extract_performers_non_superannuable_deductions(complete_pdf_text)

    # Print the extracted table text
    if performers_non_superannuation_table_text:
        print("Performers' Non-Superannuable Deductions Statutory Levy Table:")
        #print(performers_non_superannuation_table_text)

        # Format the table text
        formatted_table = format_table_non_superannuable_deductions(performers_non_superannuation_table_text, numeric_part, statement_reference)

        # Convert the formatted table to DataFrame
        df = pd.DataFrame(formatted_table)

        # Print DataFrame
        #print(df)
        
        
# Create a boolean mask to identify rows where 'Performer_Name' is either 'Contract' or 'Superannuable'
        mask = ~df['Performer_Name'].isin(['Contract', 'Superannuable'])

# Apply the mask to filter out rows that do not match the conditions
        df3 = df[mask]

# df_filtered now contains only the rows where 'Performer_Name' is neither 'Contract' nor 'Superannuable'
        
        print(df3)
    else:
        print("Performers' Non-Superannuable Deductions Statutory Levy Table not found in the PDF text.")

Performers' Non-Superannuable Deductions Statutory Levy Table not found in the PDF text.

In [48]:
df3.dtypes

Contract_ID             object
Statement_Reference     object
Performer_ID            object
Performer_Name          object
Amount                 float64
dtype: object

In [46]:
host = 'localhost'
user = 'root'
password = ''
database = 'new'

# Establish connection to MySQL
try:
    conn = mysql.connector.connect(
        user=user,
        password=password,
        host=host,
        database=database
    )
    print("Connected to MySQL database:", conn.database)
except mysql.connector.Error as err:
    print("Error connecting to MySQL:", err)
# Create a cursor object
cursor = conn.cursor()

# Define the table name
table_name = 'dashboard_nonsuperannuable'

# Query to fetch table structure
query = f"SHOW COLUMNS FROM {table_name}"

# Execute the query
cursor.execute(query)

# Fetch all rows from the result
rows = cursor.fetchall()

# Get column names and data types
column_info = [(row[0], row[1]) for row in rows]

# Create a DataFrame for displaying table structure
df_structure = pd.DataFrame(column_info, columns=['Column', 'Data Type'])

# Display the table structure
print(f"Table Structure of '{table_name}':")
print(df_structure)

Connected to MySQL database: new
Table Structure of 'dashboard_nonsuperannuable':
                Column      Data Type
0                   id        int(11)
1          Contract_ID   varchar(255)
2  Statement_Reference   varchar(255)
3         Performer_ID   varchar(255)
4       Performer_Name   varchar(255)
5               Amount  decimal(10,2)

In [47]:
df3['Amount'] = df3['Amount'].astype(float)

C:\Users\Awan\AppData\Local\Temp/ipykernel_5792/2865114571.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df3['Amount'] = df3['Amount'].astype(float)

In [53]:
df3.loc[:, 'Amount'] = df3['Amount'].astype(float)

C:\Users\Awan\anaconda3\lib\site-packages\pandas\core\indexing.py:1773: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(ilocs[0], value, pi)

In [50]:

import mysql.connector
import pandas as pd

host = 'localhost'
user = 'root'
password = ''
database = 'new'


# Establish connection to MySQL
try:
    conn = mysql.connector.connect(
        user=user,
        
        password=password,
        host=host,
        database=database
    )
    print("Connected to MySQL database:", conn.database)
except mysql.connector.Error as err:
    print("Error connecting to MySQL:", err)

# Prepare SQL insert statement
insert_statement = """
INSERT INTO dashboard_nonsuperannuable
(Contract_ID, Statement_Reference, Performer_ID, Performer_Name, Amount)
VALUES (%s, %s, %s, %s, %s)
"""

try:
    with conn.cursor() as cursor:
        # Iterate over DataFrame rows
        for index, row in df3.iterrows():
            # Extract values from DataFrame row and perform necessary conversions
            values = (
                row['Contract_ID'],
                row['Statement_Reference'],
                row['Performer_ID'],
                row['Performer_Name'],
                float(row['Amount']) if pd.notnull(row['Amount']) else None  # Convert to float (handle NaN)
            )
            
            # Execute SQL insert statement
            cursor.execute(insert_statement, values)
        
    # Commit changes to the database
    conn.commit()
    print("Data inserted successfully into MySQL table")

except Exception as e:
    print(f"Error occurred: {e}")

finally:
    # Close connection
    conn.close()

Connected to MySQL database: new
Data inserted successfully into MySQL table

# Units of Dental Activity per Performer

In [12]:
import pandas as pd
import PyPDF2
import re

def extract_text_from_pdf(pdf_path):
    text_per_page = []
    with open(pdf_path, 'rb') as file:
        pdf_reader = PyPDF2.PdfReader(file)
        num_pages = len(pdf_reader.pages)
        for page_num in range(num_pages):
            page = pdf_reader.pages[page_num]
            text = page.extract_text()
            text_per_page.append(text)
    return text_per_page

def extract_units_of_dental_activity(text_per_page):
    start_pattern = "Units of Dental Activity per Performer"
    #start_pattern = "Units of Dental Activity per Clinician"
    end_pattern = "THIS STATEMENT SHOULD BE RETAINED FOR TAX PURPOSES"

    relevant_text = ""
    for page_text in text_per_page:
        start_index = page_text.find(start_pattern)
        if start_index != -1:
            end_index = page_text.find(end_pattern, start_index)
            if end_index != -1:
                relevant_text += page_text[start_index:end_index]
            else:
                relevant_text += page_text[start_index:]
    return relevant_text

def parse_performers(text):
    performer_data = re.findall(r'\b(\d+)\s+([A-Za-z\s]+)\s+Current', text)
    performer_ids, performer_names = zip(*performer_data)
    return performer_ids, performer_names

def extract_current_financial_year_rows(text, pattern, year_col_name, amount_col_name):
    current_year_rows = []
    lines = text.strip().split('\n')
    for line in lines:
        match = re.search(pattern, line)
        if match:
            year = match.group(1) if match.group(1) else '0'  # If year is missing, consider it as '0'
            current_year_rows.append({year_col_name: year, amount_col_name: match.group(2)})
    return current_year_rows

if __name__ == "__main__":
   
    
    # Extract text from PDF
    extracted_text = extract_text_from_pdf(pdf_path)
    
    # Extract relevant dental activity units
    relevant_text = extract_units_of_dental_activity(extracted_text)
    
    # Parse performer data
    performer_ids, performer_names = parse_performers(relevant_text)
    
    # Create performer DataFrame
    df_performers = pd.DataFrame({'Contract_ID': numeric_part,'Statement_Reference':statement_reference,'Performer_ID': performer_ids, 'Name': performer_names})
    
    # Extract financial year rows
    current_year_rows = extract_current_financial_year_rows(relevant_text, 
                                                            r'Current Financial Year (\d{4}/\d{2})\s+([\d.]+)',
                                                            'Current_Financial_Year', 
                                                            'Current_Financial_Year_Amount')
    
    last_year_rows = extract_current_financial_year_rows(relevant_text, 
                                                            r'Last Financial Year (\d{4}/\d{2})\s+([\d.]+)',
                                                            'Last_Financial_Year', 
                                                            'Last_Financial_Year_Amount')

    other_year_rows = extract_current_financial_year_rows(relevant_text, 
                                                            r'Other Financial Years(?: (\d{4}/\d{2}))?\s+([\d.]+)',
                                                            'Other_Financial_Years', 
                                                            'Other_Financial_Year_Amount')

    # Create financial year DataFrames
    df_current = pd.DataFrame(current_year_rows)
    df_last = pd.DataFrame(last_year_rows)
    df_other = pd.DataFrame(other_year_rows)
    
    # Concatenate financial year DataFrames
    df_financial_years = pd.concat([df_current, df_last, df_other], axis=1)
    
    # Print combined DataFrame
    combined_df = pd.concat([df_performers, df_financial_years], axis=1)
    df4 =combined_df 
    print(df4)

NameError: name 'numeric_part' is not defined

In [44]:
import re
import pandas as pd
import mysql.connector
from mysql.connector import Error
def pdf_text_from_pdf(pdf_path):
    text_per_page = []
    with open(pdf_path, 'rb') as file:
        pdf_reader = PyPDF2.PdfReader(file)
        num_pages = len(pdf_reader.pages)
        for page_num in range(num_pages):
            page = pdf_reader.pages[page_num]
            text = page.extract_text()
            text_per_page.append(text)
    return text_per_page
def extract_statement_references_from_text(pdf_text):
    statement_reference = None  # Initialize statement reference variable
    for text in pdf_text:
        if statement_reference is None:  # Check if statement reference is not assigned yet
            statement_reference_match = re.search(r'Statement\s*Reference\s*([\d/]+)', text)
            if statement_reference_match:
                statement_reference = statement_reference_match.group(1)
                break  # Break loop after finding the first statement reference
    return statement_reference
def extract_text_from_pdf(pdf_path):
    text_per_page = []
    with open(pdf_path, 'rb') as file:
        pdf_reader = PyPDF2.PdfReader(file)
        num_pages = len(pdf_reader.pages)
        for page_num in range(num_pages):
            page = pdf_reader.pages[page_num]
            text = page.extract_text()
            text_per_page.append(text)
            # Check if the text "Contract Monthly Pay Statement" is in the extracted text
            if "Contract Monthly Pay Statement" in text:
                break  # Stop extracting text from further pages
    return text_per_page


def extract_performers_superannuation_table(pdf_text):
    # Define the start and end patterns for the table
    start_pattern = r'Performers\' Superannuation Contribution'
    end_pattern = r'Patients\' Charges'

    # Find the start and end positions of the table
    start_match = re.search(start_pattern, pdf_text)
    end_match = re.search(end_pattern, pdf_text)

    # If both start and end patterns are found, extract the table text
    if start_match and end_match:
        table_text = pdf_text[start_match.end():end_match.start()].strip()
        return table_text
    else:
        return None
def extract_rows_from_text(text):
    # Define a more flexible pattern to capture rows
    pattern = r'(\d+)\s+([A-Za-z\s]+)@?\s+([\d.]+)%\s*(-?£[\d.,]+)'
    #rows = re.findall(r'(\d+)\s+([A-Za-z\s]+)@?\s+([\d.]+)%\s+£([\d.]+)', cleaned_table_text)
    
    # Find all matches in the text
    matches = re.findall(pattern, cleaned_text)
    
    # Return a list of matched rows
    return matches

def format_table(rows, Contract_ID, statement_reference):
    formatted_rows = []
    for row in rows:
               # Extract the numeric part of the amount string and convert to float
        amount_str = re.sub(r'[^.\d]', '', row[3])  # Remove all non-numeric characters except '.'
        amount = float(amount_str)  # Convert to float
        
        formatted_row = {
            "contract_id": Contract_ID,
            "statement_reference": statement_reference,
            "performer_id": row[0],
            "name": row[1].strip(),
            "percentage": row[2],
            "amount": amount
        }
        formatted_rows.append(formatted_row)
    return formatted_rows
def extract_performers_non_superannuable_deductions(pdf_text):
    # Define the start and end patterns for the table
    start_pattern = r'Non-Superannuable Deductions\s*Statutory Levy'
    end_pattern = r'(?:Performers\' Net Pensionable Earnings|$)'  # End pattern is either end of table or next section

    # Find the start and end positions of the table
    start_match = re.search(start_pattern, pdf_text)
    end_match = re.search(end_pattern, pdf_text)

    # If both start and end patterns are found, extract the table text
    if start_match and end_match:
        table_text = pdf_text[start_match.end():end_match.start()]
        return table_text.strip()
    else:
        return None

def format_tablenon_superannuable_deductions(table_text, Contract_ID, statement_reference):
    # Extracting rows using regular expression
    rows = re.findall(r'(\d+)\s+([A-Za-z\s]+)\s+£([\d.]+)', table_text)
    

    # Formatting the rows into desired format
    formatted_rows = []
    for row in rows:
        formatted_row = {
            "Contract_ID": Contract_ID,
            "Statement_Reference": statement_reference,
            "Performer_ID": row[0],
            "Performer_Name": row[1],
            "Amount": row[2]
            
            
        }
        formatted_rows.append(formatted_row)

    return formatted_rows

def extract_units_of_dental_activity(text_per_page):
    start_pattern = "Units of Dental Activity per Performer"
    #start_pattern = "Units of Dental Activity per Clinician"
    end_pattern = "THIS STATEMENT SHOULD BE RETAINED FOR TAX PURPOSES"

    relevant_text = ""
    for page_text in text_per_page:
        start_index = page_text.find(start_pattern)
        if start_index != -1:
            end_index = page_text.find(end_pattern, start_index)
            if end_index != -1:
                relevant_text += page_text[start_index:end_index]
            else:
                relevant_text += page_text[start_index:]
    return relevant_text

def parse_performers(text):
    performer_data = re.findall(r'\b(\d+)\s+([A-Za-z\s]+)\s+Current', text)
    performer_ids, performer_names = zip(*performer_data)
    return performer_ids, performer_names

def extract_current_financial_year_rows(text, pattern, year_col_name, amount_col_name):
    current_year_rows = []
    lines = text.strip().split('\n')
    for line in lines:
        match = re.search(pattern, line)
        if match:
            year = match.group(1) if match.group(1) else '0'  # If year is missing, consider it as '0'
            current_year_rows.append({year_col_name: year, amount_col_name: match.group(2)})
    return current_year_rows


if __name__ == "__main__":
    # Extract the table text
    pdf_text = pdf_text_from_pdf(pdf_path)
    complete_pdf_text = "\n".join(pdf_text)
    performers_superannuation_table_text = extract_performers_superannuation_table(complete_pdf_text)
    cleaned_table_text = re.sub(r'\(\d+\)', '', performers_superannuation_table_text)
    pattern = r"Performers' Added Benefit.*$"

    # Use regex to substitute the matched pattern with an empty string
    cleaned_text = re.sub(pattern, '', cleaned_table_text, flags=re.DOTALL)

    # Trim any leading or trailing whitespace
    cleaned_text = cleaned_text.strip()
    



    
    pdf_text = pdf_text_from_pdf(pdf_path)
    statement_reference = extract_statement_references_from_text(pdf_text)
    
    if statement_reference:
        print("Extracted Statement Reference:", statement_reference)
    else:
        print("No Statement Reference found in the PDF.")
    
    extracted_text = extract_text_from_pdf(pdf_path)
    found_text = False  # Flag to check if the desired text is found
    contract_monthly_pay_statement_text = ""  # Initialize empty string to store the desired text
    for page_num, text in enumerate(extracted_text, start=1):
        if found_text:
            contract_monthly_pay_statement_text += text.strip() + "\n---\n"  # Append the text to the output
        elif "Contract Monthly Pay Statement" in text:
            found_text = True  # Set the flag to True when the desired text is found
            contract_monthly_pay_statement_text += text.strip() + "\n---\n"  # Append the text to the output

    extracted_text = extract_text_from_pdf(pdf_path)
    found_start = False
    contract = ""  # Initialize empty string to store the desired text
    for page_num, text in enumerate(extracted_text, start=1):
        if found_start:
            if "CONTRACT" in text:
                break
            contract += text.strip() + "\n"
        elif "CONTRACT" in text:
            found_start = True
            # Find the index of the start of "Contract Monthly Pay Statement" and "CONTRACT"
            start_index = text.find("CONTRACT") + len("CONTRACT")
            end_index = text.find("If ")
            # Append the text between these indices
            contract += text[start_index:end_index].strip() + "\n"

    # Splitting the contract string into Contract_ID and Contract_Name
    contract_lines = contract.split("\n", 1)  # Splitting into two parts at the first newline

    # Assuming the first part is Contract_ID and the second part is Contract_Name
    contract_id = contract_lines[0].strip()
    Contract_Name = contract_lines[1].strip()
    Contract_ID = ''.join(filter(str.isdigit, contract_id))
    print("Contract_ID:", Contract_ID)
    # Extract rows using the updated pattern
    rows = extract_rows_from_text(cleaned_text)

    
    # Format the extracted rows into DataFrame
    formatted_table = format_table(rows, Contract_ID, statement_reference)
    df2 = pd.DataFrame(formatted_table)
    # Convert data types
    df2['contract_id'] = df2['contract_id'].astype(str)
    df2['statement_reference'] = df2['statement_reference'].astype(str)
    df2['performer_id'] = df2['performer_id'].astype(str)
    df2['name'] = df2['name'].astype(str)
    df2['percentage'] = df2['percentage'].astype(float)
    df2['amount'] = df2['amount'].astype(float)
    # Display the DataFrame
    
    print("Performers' Superannution Deductions Statutory Levy Table:")
    print(df2)
    
    performers_non_superannuation_table_text = extract_performers_non_superannuable_deductions(complete_pdf_text)

    # Print the extracted table text
    if performers_non_superannuation_table_text:
        print("Performers' Non-Superannuable Deductions Statutory Levy Table:")
        #print(performers_non_superannuation_table_text)

        # Format the table text
        formatted_table = format_table_non_superannuable_deductions(performers_non_superannuation_table_text, Contract_ID, statement_reference)

        # Convert the formatted table to DataFrame
        df = pd.DataFrame(formatted_table)

        # Print DataFrame
        #print(df)
        
        
# Create a boolean mask to identify rows where 'Performer_Name' is either 'Contract' or 'Superannuable'
        mask = ~df['Performer_Name'].isin(['Contract', 'Superannuable'])

# Apply the mask to filter out rows that do not match the conditions
        df3 = df[mask]

# df_filtered now contains only the rows where 'Performer_Name' is neither 'Contract' nor 'Superannuable'
        
        print(df3)
    else:
        print("Performers' Non-Superannuable Deductions Statutory Levy Table not found in the PDF text.")
    
    relevant_text = extract_units_of_dental_activity(pdf_text)
    
    # Parse performer data
    performer_ids, performer_names = parse_performers(relevant_text)
    
    # Create performer DataFrame
    df_performers = pd.DataFrame({'Contract_ID': Contract_ID,'Statement_Reference':statement_reference,'Performer_ID': performer_ids, 'Name': performer_names})
    
    # Extract financial year rows
    current_year_rows = extract_current_financial_year_rows(relevant_text, 
                                                            r'Current Financial Year (\d{4}/\d{2})\s+([\d.]+)',
                                                            'Current_Financial_Year', 
                                                            'Current_Financial_Year_Amount')
    
    last_year_rows = extract_current_financial_year_rows(relevant_text, 
                                                            r'Last Financial Year (\d{4}/\d{2})\s+([\d.]+)',
                                                            'Last_Financial_Year', 
                                                            'Last_Financial_Year_Amount')

    other_year_rows = extract_current_financial_year_rows(relevant_text, 
                                                            r'Other Financial Years(?: (\d{4}/\d{2}))?\s+([\d.]+)',
                                                            'Other_Financial_Years', 
                                                            'Other_Financial_Year_Amount')

    # Create financial year DataFrames
    df_current = pd.DataFrame(current_year_rows)
    df_last = pd.DataFrame(last_year_rows)
    df_other = pd.DataFrame(other_year_rows)
    
    # Concatenate financial year DataFrames
    df_financial_years = pd.concat([df_current, df_last, df_other], axis=1)
    
    # Print combined DataFrame
    combined_df = pd.concat([df_performers, df_financial_years], axis=1)
    df4 =combined_df 
    

    df4['Current_Financial_Year_Amount'] = df4['Current_Financial_Year_Amount'].astype(float)
    df4['Last_Financial_Year_Amount'] = df4['Last_Financial_Year_Amount'].astype(float)
    df4['Other_Financial_Year_Amount'] = df4['Other_Financial_Year_Amount'].astype(float)
    df4.rename(columns={'Other_Financial_Year_Amount': 'Other_Finacial_Year_Amount'}, inplace=True)
    print("Performers' Units of Dental Activity Table:")
    print(df4)
    
    
    host = 'localhost'
    user = 'root'
    password = ''
    database = 'new'


    # Establish connection to MySQL
    try:
        conn = mysql.connector.connect(
            user=user,
        
            password=password,
            host=host,
            database=database
        )
        print("Connected to MySQL database:", conn.database)
    except mysql.connector.Error as err:
        print("Error connecting to MySQL:", err)

    # Prepare SQL insert statement
    insert_statement = """
    INSERT INTO dashboard_units_details
    (Contract_ID, Statement_Reference, Performer_ID, Name, Current_Financial_Year, 
    Current_Financial_Year_Amount, Last_Financial_Year, Last_Financial_Year_Amount, 
    Other_Finacial_Years, Other_Finacial_Year_Amount)
    VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
    """

    try:
        with conn.cursor() as cursor:
        # Iterate over DataFrame rows
            for index, row in df4.iterrows():
            # Extract values from DataFrame row and perform necessary conversions
                values = (
                    row['Contract_ID'],
                    row['Statement_Reference'],
                    row['Performer_ID'],
                    row['Name'],
                    row['Current_Financial_Year'],
                    float(row['Current_Financial_Year_Amount']),  # Convert to float
                    row['Last_Financial_Year'],
                    float(row['Last_Financial_Year_Amount']),  # Convert to float
                    row['Other_Financial_Years'],
                    float(row['Other_Finacial_Year_Amount'])  # Convert to float
                )
            
            # Execute SQL insert statement
                cursor.execute(insert_statement, values)
        
    # Commit changes to the database
        conn.commit()
        print("Data Performers' Units of Dental Activity Table inserted successfully into MySQL table")

    except Exception as e:
        print(f"Error occurred: {e}")
        
        
    insert_statement = """
    INSERT INTO dashboard_superannuationdetails
    (contract_id, statement_reference, name, percentage, amount, performer_id)
    VALUES (%s, %s, %s, %s, %s, %s)
    """

    try:
        with conn.cursor() as cursor:
        # Iterate over DataFrame rows
            for index, row in df2.iterrows():
            # Extract values from DataFrame row and perform necessary conversions
                values = (
                    row['contract_id'],
                    row['statement_reference'],
                    row['name'],
                    row['percentage'],  
                    row['amount'],
                    row['performer_id']
                )
            
            # Execute SQL insert statement
                cursor.execute(insert_statement, values)
        
    # Commit changes to the database
        conn.commit()
        print("Data of Performers' Superannution Deductions Statutory Levy Table inserted successfully into MySQL table")

    except Exception as e:
        print(f"Error occurred: {e}")

Extracted Statement Reference: 2324/04
Contract_ID: 3954630007
Performers' Superannution Deductions Statutory Levy Table:
   contract_id statement_reference performer_id                 name  \
0   3954630007             2324/04       364207           AJ ABULHAB
1   3954630007             2324/04       114847             Coughlan
2   3954630007             2324/04       651133             S GHAURI
3   3954630007             2324/04       887048  I HAMDY ABD ELRAZEK
4   3954630007             2324/04       887048  I HAMDY ABD ELRAZEK
5   3954630007             2324/04       887048  I HAMDY ABD ELRAZEK
6   3954630007             2324/04       786616       AK JAISINGHANI
7   3954630007             2324/04       453390             JS MALIK
8   3954630007             2324/04       107389             ZM MIRZA
9   3954630007             2324/04       107389             ZM MIRZA
10  3954630007             2324/04       476617            AD MISTRY
11  3954630007             2324/04       111766             Ja Malik
12  3954630007             2324/04       111766             Ja Malik
13  3954630007             2324/04       111766             Ja Malik
14  3954630007             2324/04       623504              JS UBHI
15  3954630007             2324/04       115616               NZ ZIA
16  3954630007             2324/04       115616               NZ ZIA

    percentage  amount
0         11.6    4.75
1          7.7    3.80
2          5.1    0.23
3          5.0   11.80
4          5.1   12.90
5          5.1    4.12
6          9.8    0.82
7          5.1    4.30
8          5.1    0.18
9          5.1    0.16
10         6.8    2.84
11         9.3   79.10
12         9.8   45.50
13         9.8   18.54
14         6.1    4.21
15         9.8    1.00
16         9.8    1.85
Performers' Non-Superannuable Deductions Statutory Levy Table:
   Contract_ID Statement_Reference Performer_ID        Performer_Name Amount
1   3954630007             2324/04       364207            AJ ABULHAB   0.19
2   3954630007             2324/04       440914           S CHANDNANI   0.02
3   3954630007             2324/04       114847              Coughlan   0.28
4   3954630007             2324/04       651133              S GHAURI   0.02
5   3954630007             2324/04       887048   I HAMDY ABD ELRAZEK   0.21
6   3954630007             2324/04       786616        AK JAISINGHANI   0.04
7   3954630007             2324/04       105667  KRISHNA MURTHY GOWDA   2.99
8   3954630007             2324/04       453390              JS MALIK   0.38
9   3954630007             2324/04       107389              ZM MIRZA   0.02
10  3954630007             2324/04       476617             AD MISTRY   0.28
11  3954630007             2324/04       111766              Ja Malik   1.92
12  3954630007             2324/04       943436              L NAJJAR   2.35
13  3954630007             2324/04       604143             MT PAREKH   1.44
14  3954630007             2324/04       114436                  SAFI   0.74
15  3954630007             2324/04       106669              AS SINGH   0.02
16  3954630007             2324/04       623504               JS UBHI   0.28
17  3954630007             2324/04       115616                NZ ZIA   0.65
Performers' Units of Dental Activity Table:
  Contract_ID Statement_Reference Performer_ID         Name  \
0  3954630007             2324/04       440914  S CHANDNANI
1  3954630007             2324/04       651133     S GHAURI
2  3954630007             2324/04       476617    AD MISTRY
3  3954630007             2324/04       111766     Ja Malik
4  3954630007             2324/04       604143    MT PAREKH
5  3954630007             2324/04       114436         SAFI
6  3954630007             2324/04       695483     F SATTAR

  Current_Financial_Year  Current_Financial_Year_Amount Last_Financial_Year  \
0                2023/24                           14.4             2022/23
1                2023/24                            6.0             2022/23
2                2023/24                            3.6             2022/23
3                2023/24                           12.8             2022/23
4                2023/24                           13.2             2022/23
5                2023/24                            7.2             2022/23
6                2023/24                            4.6             2022/23

   Last_Financial_Year_Amount Other_Financial_Years  \
0                         0.0                     0
1                         0.0                     0
2                         0.0                     0
3                         0.0                     0
4                         0.0                     0
5                         0.0                     0
6                         0.0                     0

   Other_Finacial_Year_Amount
0                         0.0
1                         0.0
2                         0.0
3                         0.0
4                         0.0
5                         0.0
6                         0.0
Connected to MySQL database: new
Data Performers' Units of Dental Activity Table inserted successfully into MySQL table
Data of Performers' Superannution Deductions Statutory Levy Table inserted successfully into MySQL table

# Database

In [18]:
import mysql.connector
from mysql.connector import Error

# Database connection parameters
host = 'localhost'
user = 'root'
password = ''
database = 'new'

try:
    # Establish connection to MySQL database
    conn = mysql.connector.connect(
        host=host,
        user=user,
        password=password,
        database=database
    )
    
    if conn.is_connected():
        print("Connected to the database")

except Error as e:
    print(f"Error: {e}")

Connected to the database

In [19]:
import mysql.connector
from mysql.connector import Error

# Database connection parameters
host = 'localhost'
user = 'root'
password = ''
database = 'new'

try:
    # Establish connection to MySQL database
    conn = mysql.connector.connect(\
        host=host,
        user=user,
        password=password,
        database=database
    )
    
    if conn.is_connected():
        print("Connected to the database")
        
        # Create a cursor object using cursor() method
        cursor = conn.cursor()
        
        # Execute the SQL query to show tables
        cursor.execute("SHOW TABLES")
        
        # Fetch all the rows from the executed query
        tables = cursor.fetchall()
        
        print("Tables in the database:")
        for table in tables:
            print(table[0])
            
except Error as e:
    print(f"Error: {e}")

Connected to the database
Tables in the database:
auth_group
auth_group_permissions
auth_permission
contract_id
dashboard_adminhod
dashboard_compasscredentials
dashboard_contract_details
dashboard_customuser
dashboard_customuser_groups
dashboard_customuser_user_permissions
dashboard_nonsuperannuable
dashboard_staffs
dashboard_superannuationdetails
dashboard_units_details
data_report
django_admin_log
django_content_type
django_migrations
django_session
performers

In [17]:
host = 'localhost'
user = 'root'
password = ''
database = 'new'

# Establish connection to MySQL
try:
    conn = mysql.connector.connect(
        user=user,
        password=password,
        host=host,
        database=database
    )
    print("Connected to MySQL database:", conn.database)
except mysql.connector.Error as err:
    print("Error connecting to MySQL:", err)
# Create a cursor object
cursor = conn.cursor()

# Define the table name
table_name = 'dashboard_units_details'

# Query to fetch table structure
query = f"SHOW COLUMNS FROM {table_name}"

# Execute the query
cursor.execute(query)

# Fetch all rows from the result
rows = cursor.fetchall()

# Get column names and data types
column_info = [(row[0], row[1]) for row in rows]

# Create a DataFrame for displaying table structure
df_structure = pd.DataFrame(column_info, columns=['Column', 'Data Type'])

# Display the table structure
print(f"Table Structure of '{table_name}':")
print(df_structure)

Error connecting to MySQL: 2003 (HY000): Can't connect to MySQL server on 'localhost:3306' (10061)

NameError: name 'conn' is not defined

In [303]:
df4['Current_Financial_Year_Amount'] = df4['Current_Financial_Year_Amount'].astype(float)
df4['Last_Financial_Year_Amount'] = df4['Last_Financial_Year_Amount'].astype(float)
df4['Other_Financial_Year_Amount'] = df4['Other_Financial_Year_Amount'].astype(float)
df4.rename(columns={'Other_Financial_Year_Amount': 'Other_Finacial_Year_Amount'}, inplace=True)

In [22]:
import mysql.connector
import pandas as pd

host = 'localhost'
user = 'root'
password = ''
database = 'new'


# Establish connection to MySQL
try:
    conn = mysql.connector.connect(
        user=user,
        
        password=password,
        host=host,
        database=database
    )
    print("Connected to MySQL database:", conn.database)
except mysql.connector.Error as err:
    print("Error connecting to MySQL:", err)

# Prepare SQL insert statement
insert_statement = """
INSERT INTO dashboard_units_details
(Contract_ID, Statement_Reference, Performer_ID, Name, Current_Financial_Year, 
 Current_Financial_Year_Amount, Last_Financial_Year, Last_Financial_Year_Amount, 
 Other_Finacial_Years, Other_Finacial_Year_Amount)
VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
"""

try:
    with conn.cursor() as cursor:
        # Iterate over DataFrame rows
        for index, row in df4.iterrows():
            # Extract values from DataFrame row and perform necessary conversions
            values = (
                row['Contract_ID'],
                row['Statement_Reference'],
                row['Performer_ID'],
                row['Name'],
                row['Current_Financial_Year'],
                float(row['Current_Financial_Year_Amount']),  # Convert to float
                row['Last_Financial_Year'],
                float(row['Last_Financial_Year_Amount']),  # Convert to float
                row['Other_Financial_Years'],
                float(row['Other_Finacial_Year_Amount'])  # Convert to float
            )
            
            # Execute SQL insert statement
            cursor.execute(insert_statement, values)
        
    # Commit changes to the database
    conn.commit()
    print("Data inserted successfully into MySQL table")

except Exception as e:
    print(f"Error occurred: {e}")

finally:
    # Close connection
    conn.close()

Connected to MySQL database: new
Data inserted successfully into MySQL table

# performer Superannuation

In [36]:
df2['contract_id']=df2['contract_id'].astype(str)
df2['percentage']=df2['percentage'].astype(float)
df2['statement_Reference']=df2['statement_reference'].astype(str)
df2['performer_id']=df2['performer_id'].astype(str)
df2['name']=df2['name'].astype(str)
df2['amount']=df2['amount'].astype(float)

In [37]:
df2.dtypes

contract_id             object
statement_reference     object
performer_id            object
name                    object
percentage             float64
amount                 float64
statement_Reference     object
dtype: object

In [312]:
host = 'localhost'
user = 'root'
password = ''
database = 'new'

# Establish connection to MySQL
try:
    conn = mysql.connector.connect(
        user=user,
        password=password,
        host=host,
        database=database
    )
    print("Connected to MySQL database:", conn.database)
except mysql.connector.Error as err:
    print("Error connecting to MySQL:", err)
# Create a cursor object
cursor = conn.cursor()

# Define the table name
table_name = 'dashboard_superannuationdetails'

# Query to fetch table structure
query = f"SHOW COLUMNS FROM {table_name}"

# Execute the query
cursor.execute(query)

# Fetch all rows from the result
rows = cursor.fetchall()

# Get column names and data types
column_info = [(row[0], row[1]) for row in rows]

# Create a DataFrame for displaying table structure
df_structure = pd.DataFrame(column_info, columns=['Column', 'Data Type'])

# Display the table structure
print(f"Table Structure of '{table_name}':")
print(df_structure)

Connected to MySQL database: new
Table Structure of 'dashboard_superannuationdetails':
                Column      Data Type
0                   id        int(11)
1          contract_id   varchar(100)
2  statement_reference   varchar(100)
3                 name   varchar(255)
4           percentage  decimal(10,2)
5               amount  decimal(10,2)
6         performer_id   varchar(100)

In [32]:
import re
import pandas as pd


def extract_performers_superannuation_table(pdf_text):
    # Define the start and end patterns for the table
    start_pattern = r'Performers\' Superannuation Contribution'
    end_pattern = r'Patients\' Charges'

    # Find the start and end positions of the table
    start_match = re.search(start_pattern, pdf_text)
    end_match = re.search(end_pattern, pdf_text)

    # If both start and end patterns are found, extract the table text
    if start_match and end_match:
        table_text = pdf_text[start_match.end():end_match.start()].strip()
        return table_text
    else:
        return None
if __name__ == "__main__":
    # Extract the table text
    pdf_text = pdf_text_from_pdf(pdf_path)
    complete_pdf_text = "\n".join(pdf_text)
    performers_superannuation_table_text = extract_performers_superannuation_table(complete_pdf_text)
    cleaned_table_text = re.sub(r'\(\d+\)', '', performers_superannuation_table_text)
    pattern = r"Performers' Added Benefit.*$"

    # Use regex to substitute the matched pattern with an empty string
    cleaned_text = re.sub(pattern, '', cleaned_table_text, flags=re.DOTALL)

    # Trim any leading or trailing whitespace
    cleaned_text = cleaned_text.strip()
    
def extract_rows_from_text(text):
    # Define a more flexible pattern to capture rows
    pattern = r'(\d+)\s+([A-Za-z\s]+)@?\s+([\d.]+)%\s*(-?£[\d.,]+)'
    #rows = re.findall(r'(\d+)\s+([A-Za-z\s]+)@?\s+([\d.]+)%\s+£([\d.]+)', cleaned_table_text)
    
    # Find all matches in the text
    matches = re.findall(pattern, cleaned_text)
    
    # Return a list of matched rows
    return matches

def format_table(rows, numeric_part, statement_reference):
    formatted_rows = []
    for row in rows:
               # Extract the numeric part of the amount string and convert to float
        amount_str = re.sub(r'[^.\d]', '', row[3])  # Remove all non-numeric characters except '.'
        amount = float(amount_str)  # Convert to float
        
        formatted_row = {
            "contract_id": Contract_ID,
            "statement_reference": statement_reference,
            "performer_id": row[0],
            "name": row[1].strip(),
            "percentage": row[2],
            "amount": amount
        }
        formatted_rows.append(formatted_row)
    return formatted_rows

if __name__ == "__main__":
    
    # Extract rows using the updated pattern
    rows = extract_rows_from_text(cleaned_text)

    
    # Format the extracted rows into DataFrame
    formatted_table = format_table(rows, Contract_ID, statement_reference)
    df2 = pd.DataFrame(formatted_table)
    
    # Display the DataFrame
    print(df2)

   contract_id statement_reference performer_id                 name  \
0   3954630007             2324/04       364207           AJ ABULHAB
1   3954630007             2324/04       114847             Coughlan
2   3954630007             2324/04       651133             S GHAURI
3   3954630007             2324/04       887048  I HAMDY ABD ELRAZEK
4   3954630007             2324/04       887048  I HAMDY ABD ELRAZEK
5   3954630007             2324/04       887048  I HAMDY ABD ELRAZEK
6   3954630007             2324/04       786616       AK JAISINGHANI
7   3954630007             2324/04       453390             JS MALIK
8   3954630007             2324/04       107389             ZM MIRZA
9   3954630007             2324/04       107389             ZM MIRZA
10  3954630007             2324/04       476617            AD MISTRY
11  3954630007             2324/04       111766             Ja Malik
12  3954630007             2324/04       111766             Ja Malik
13  3954630007             2324/04       111766             Ja Malik
14  3954630007             2324/04       623504              JS UBHI
15  3954630007             2324/04       115616               NZ ZIA
16  3954630007             2324/04       115616               NZ ZIA

   percentage  amount
0       11.60    4.75
1        7.70    3.80
2        5.10    0.23
3        5.00   11.80
4        5.10   12.90
5        5.10    4.12
6        9.80    0.82
7        5.10    4.30
8        5.10    0.18
9        5.10    0.16
10       6.80    2.84
11       9.30   79.10
12       9.80   45.50
13       9.80   18.54
14       6.10    4.21
15       9.80    1.00
16       9.80    1.85

In [33]:
df2.dtypes

contract_id             object
statement_reference     object
performer_id            object
name                    object
percentage              object
amount                 float64
dtype: object

In [38]:
import re
import pandas as pd

def extract_performers_superannuation_table(pdf_text):
    # Define the start and end patterns for the table
    start_pattern = r'Performers\' Superannuation Contribution'
    end_pattern = r'Patients\' Charges'

    # Find the start and end positions of the table
    start_match = re.search(start_pattern, pdf_text)
    end_match = re.search(end_pattern, pdf_text)

    # If both start and end patterns are found, extract the table text
    if start_match and end_match:
        table_text = pdf_text[start_match.end():end_match.start()].strip()
        return table_text
    else:
        return None

def extract_rows_from_text(text):
    # Define a more flexible pattern to capture rows
    pattern = r'(\d+)\s+([A-Za-z\s]+)@?\s+([\d.]+)%\s*(-?£[\d.,]+)'
    
    # Find all matches in the text
    matches = re.findall(pattern, text)
    
    # Return a list of matched rows
    return matches

def format_table(rows, contract_id, statement_reference):
    formatted_rows = []
    for row in rows:
        # Extract the numeric part of the amount string and convert to float
        amount_str = re.sub(r'[^.\d]', '', row[3])  # Remove all non-numeric characters except '.'
        amount = float(amount_str)  # Convert to float
        
        formatted_row = {
            "contract_id": str(contract_id),
            "statement_reference": str(statement_reference),
            "performer_id": str(row[0]),
            "name": row[1].strip(),
            "percentage": float(row[2]),
            "amount": amount
        }
        formatted_rows.append(formatted_row)
    return formatted_rows

if __name__ == "__main__":
    # Extract the table text
    pdf_text = pdf_text_from_pdf(pdf_path)
    complete_pdf_text = "\n".join(pdf_text)
    performers_superannuation_table_text = extract_performers_superannuation_table(complete_pdf_text)
    
    if performers_superannuation_table_text:
        cleaned_table_text = re.sub(r'\(\d+\)', '', performers_superannuation_table_text)
        pattern = r"Performers' Added Benefit.*$"

        # Use regex to substitute the matched pattern with an empty string
        cleaned_text = re.sub(pattern, '', cleaned_table_text, flags=re.DOTALL)

        # Trim any leading or trailing whitespace
        cleaned_text = cleaned_text.strip()
        
        # Extract rows using the updated pattern
        rows = extract_rows_from_text(cleaned_text)

        # Format the extracted rows into a list of dictionaries
        formatted_table = format_table(rows, Contract_ID, statement_reference)
        
        # Create DataFrame with specified data types
        df2 = pd.DataFrame(formatted_table, dtype={
            'contract_id': str,
            'statement_reference': str,
            'performer_id': str,
            'name': str,
            'percentage': float,
            'amount': float
        })
        
        # Display the DataFrame
        print(df2)

TypeError: object of type 'type' has no len()

In [39]:
import re
import pandas as pd

def extract_performers_superannuation_table(pdf_text):
    # Define the start and end patterns for the table
    start_pattern = r'Performers\' Superannuation Contribution'
    end_pattern = r'Patients\' Charges'

    # Find the start and end positions of the table
    start_match = re.search(start_pattern, pdf_text)
    end_match = re.search(end_pattern, pdf_text)

    # If both start and end patterns are found, extract the table text
    if start_match and end_match:
        table_text = pdf_text[start_match.end():end_match.start()].strip()
        return table_text
    else:
        return None

def extract_rows_from_text(text):
    # Define a more flexible pattern to capture rows
    pattern = r'(\d+)\s+([A-Za-z\s]+)@?\s+([\d.]+)%\s*(-?£[\d.,]+)'
    
    # Find all matches in the text
    matches = re.findall(pattern, text)
    
    # Return a list of matched rows
    return matches

def format_table(rows, contract_id, statement_reference):
    formatted_rows = []
    for row in rows:
        # Extract the numeric part of the amount string and convert to float
        amount_str = re.sub(r'[^.\d]', '', row[3])  # Remove all non-numeric characters except '.'
        amount = float(amount_str)  # Convert to float
        
        formatted_row = {
            "contract_id": str(contract_id),
            "statement_reference": str(statement_reference),
            "performer_id": str(row[0]),
            "name": row[1].strip(),
            "percentage": float(row[2]),
            "amount": amount
        }
        formatted_rows.append(formatted_row)
    return formatted_rows

if __name__ == "__main__":
    # Extract the table text
    pdf_text = pdf_text_from_pdf(pdf_path)
    complete_pdf_text = "\n".join(pdf_text)
    performers_superannuation_table_text = extract_performers_superannuation_table(complete_pdf_text)
    
    if performers_superannuation_table_text:
        cleaned_table_text = re.sub(r'\(\d+\)', '', performers_superannuation_table_text)
        pattern = r"Performers' Added Benefit.*$"

        # Use regex to substitute the matched pattern with an empty string
        cleaned_text = re.sub(pattern, '', cleaned_table_text, flags=re.DOTALL)

        # Trim any leading or trailing whitespace
        cleaned_text = cleaned_text.strip()
        
        # Extract rows using the updated pattern
        rows = extract_rows_from_text(cleaned_text)

        # Format the extracted rows into a list of dictionaries
        formatted_table = format_table(rows, Contract_ID, statement_reference)
        
        # Create DataFrame without specifying dtype
        df2 = pd.DataFrame(formatted_table)
        
        # Convert data types
        df2['contract_id'] = df2['contract_id'].astype(str)
        df2['statement_reference'] = df2['statement_reference'].astype(str)
        df2['performer_id'] = df2['performer_id'].astype(str)
        df2['name'] = df2['name'].astype(str)
        df2['percentage'] = df2['percentage'].astype(float)
        df2['amount'] = df2['amount'].astype(float)
        
        # Display the DataFrame
        print(df2)

   contract_id statement_reference performer_id                 name  \
0   3954630007             2324/04       364207           AJ ABULHAB
1   3954630007             2324/04       114847             Coughlan
2   3954630007             2324/04       651133             S GHAURI
3   3954630007             2324/04       887048  I HAMDY ABD ELRAZEK
4   3954630007             2324/04       887048  I HAMDY ABD ELRAZEK
5   3954630007             2324/04       887048  I HAMDY ABD ELRAZEK
6   3954630007             2324/04       786616       AK JAISINGHANI
7   3954630007             2324/04       453390             JS MALIK
8   3954630007             2324/04       107389             ZM MIRZA
9   3954630007             2324/04       107389             ZM MIRZA
10  3954630007             2324/04       476617            AD MISTRY
11  3954630007             2324/04       111766             Ja Malik
12  3954630007             2324/04       111766             Ja Malik
13  3954630007             2324/04       111766             Ja Malik
14  3954630007             2324/04       623504              JS UBHI
15  3954630007             2324/04       115616               NZ ZIA
16  3954630007             2324/04       115616               NZ ZIA

    percentage  amount
0         11.6    4.75
1          7.7    3.80
2          5.1    0.23
3          5.0   11.80
4          5.1   12.90
5          5.1    4.12
6          9.8    0.82
7          5.1    4.30
8          5.1    0.18
9          5.1    0.16
10         6.8    2.84
11         9.3   79.10
12         9.8   45.50
13         9.8   18.54
14         6.1    4.21
15         9.8    1.00
16         9.8    1.85

In [41]:
import mysql.connector
import pandas as pd

host = 'localhost'
user = 'root'
password = ''
database = 'new'


# Establish connection to MySQL
try:
    conn = mysql.connector.connect(
        user=user,
        
        password=password,
        host=host,
        database=database
    )
    print("Connected to MySQL database:", conn.database)
except mysql.connector.Error as err:
    print("Error connecting to MySQL:", err)

# Prepare SQL insert statement
insert_statement = """
INSERT INTO dashboard_superannuationdetails
(contract_id, statement_reference, name, percentage, amount, performer_id)
VALUES (%s, %s, %s, %s, %s, %s)
"""

try:
    with conn.cursor() as cursor:
        # Iterate over DataFrame rows
        for index, row in df2.iterrows():
            # Extract values from DataFrame row and perform necessary conversions
            values = (
                row['contract_id'],
                row['statement_reference'],
                row['name'],
                row['percentage'],  
                row['amount'],
                row['performer_id']
            )
            
            # Execute SQL insert statement
            cursor.execute(insert_statement, values)
        
    # Commit changes to the database
    conn.commit()
    print("Data inserted successfully into MySQL table")

except Exception as e:
    print(f"Error occurred: {e}")
finally:
    # Close connection
    conn.close()

Connected to MySQL database: new
Data inserted successfully into MySQL table